env:
  browser: true
  es2021: true
  jest: true
extends: 
  - airbnb-base
  - plugin:react/recommended
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  react/prop-types: off
  default-param-last: off
  require-yield: off
  